Audio server plugin binding
RustAudio/coreaudio-sys pull request #93
Opened 2024-01-03 12:13 UTC by xiaopengli89

2024-01-03 16:06 UTC, simlay requested changes
Looks good. I put this through [`cargo semver-checks`](https://crates.io/crates/cargo-semver-checks) and I think this is a non-breaking change. Could you bump [the `version` to `0.2.15`](https://github.com/RustAudio/coreaudio-sys/blob/412f4f12403102026fb06bc5e5770175ee95296e/Cargo.toml#L3). I'll merge it and it'll get released to by CI to crates.io.

2024-01-04 06:48 UTC, xiaopengli89 commented
> Looks good. I put this through [`cargo semver-checks`](https://crates.io/crates/cargo-semver-checks) and I think this is a non-breaking change. Could you bump [the `version` to `0.2.15`](https://github.com/RustAudio/coreaudio-sys/blob/412f4f12403102026fb06bc5e5770175ee95296e/Cargo.toml#L3). I'll merge it and it'll get released to by CI to crates.io.

Done.

2024-01-04 14:49 UTC, simlay approved these changes

2024-01-04 14:50 UTC, merged

2024-01-04 20:16 UTC, simlay commented
[`0.2.15` has been published to crates.io](https://crates.io/crates/coreaudio-sys/0.2.15).